# version: '3.5'

# services:

#   angular-service:
#     container_name: a07_front
#     build: ./dev
#     volumes:
#       - './esmc_front:/usr/src/app'
#     ports:
#       - '4200:4200'

version: "3"

services:
    # a07_front:
    a07_front:
      #container_name: a07_web
      container_name: a07_front
      #hostname: dp-senyo
      # image: esmc-web:v1
      # image: perce26/entrersortie:a07_front
      build:
        context: .
        dockerfile: Dockerfile
      restart: always
      #command: tail -F anyts
      ports:
       #- "3000:3000"
       - "4500:80"
      #environment:
       #- API_BASE_URL=http://160.242.199.14:8888
      networks:
        - my-srv-net

networks:
  my-srv-net:
    # external:
        name: my-ng-net
